services:
  mongodb:
    image: mongo:7
    container_name: game-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo_data:/data/db
    networks:
      - game-network

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: game-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    networks:
      - game-network

volumes:
  mongo_data:

networks:
  game-network:
    driver: bridge