spring:
  application:
    name: match-service

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/matchdb}
      auto-index-creation: true

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:admin}
    password: ${SPRING_RABBITMQ_PASSWORD:admin123}

server:
  port: 8081

matchmaking:
  pool-size: ${MATCHMAKING_POOL_SIZE:10}
  rating-threshold: ${MATCHMAKING_RATING_THRESHOLD:100}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.gaming.match: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.amqp: DEBUG